#!/bin/sh
#
###################################################################
# Postallow - Automatic Postcreen Whitelist / Blacklist Generator #
# https://github.com/lquidfire/postallow                          #
# Originally by Steve Jenkins (https://www.stevejenkins.com/)     #
# Renamed and updated in 2025 by Edmund Lodewijks                 #
###################################################################

version="3.9"
lastupdated="20 May 2025"

# Usage: 1) Place entire /postallow directory in /usr/local/scripts
#	 2) Move (and modify, if needed) postallow.conf to /etc
#	 3) Run /usr/local/scripts/postallow
# Optional config file passed via command line overrides the default config file location.
#
# Requires SPF-Tools (https://github.com/lquidfire/spf-tools)
# Please update your copy of spf-tools whenever you update Postallow
#
# Thanks to `nabbi` for Perl CIDR integration.
# Thanks to Steve Jenkins (https://www.stevejenkins.com/) for the orignal version
#           (called Postwhite).
# Thanks to Mike Miller (mmiller@mgm51.com) for gallowlist.sh script.
# Thanks to Jan Sarenik for SPF-Tools.
# Thanks to Jose Borges Ferreira for IPv4 normalization help.
# Thanks to Ricardo Iván Vieitez Parra for improved error reporting, normalization, conf file
#           improvements, and removal of bash-isms so that script is usable on more systems.
# Thanks to Steve Cook for Yahoo! IP scraping help.
# Thanks to all the additional contributors on GitHub!
#
# USER-DEFINABLE OPTIONS AND CUSTOM HOSTS STORED IN /etc/postallow.conf
# CONFIGURATION FILE CAN ALSO BE PASSED FROM COMMAND LINE
#
# NO NEED TO EDIT PAST THIS LINE
#
#################################################################

permit_line_v4="%s\tpermit\n"
reject_line_v4="%s\treject\n"

permit_line_v6="${permit_line_v4}"
reject_line_v6="${reject_line_v4}"

# Abort script on error (FYI: enabling will cause script to exit silently if mailer has no valid results)
set -e

if ! aggregateCIDR=$(which aggregateCIDR.pl) ; then
    echo "fatal: unable to locate aggregateCIDR.pl"
    echo "https://github.com/lquidfire/route-summarization"
    exit 1
fi

if [ x"$reload_postfix" = x"yes" ] ; then
	if ! postmap=$(which postmap) ; then
		echo "fatal: unable to locate postmap"
		exit 1
	fi
fi

printf "Starting Postallow v$version ($lastupdated)\n"

# Check for passed config file
if [ -n "$1" ]; then
	config_file="$1"
elif [ -f "/etc/postallow.conf" ]; then
    config_file="/etc/postallow.conf"
elif [ -f "/etc/postallow/postallow.conf" ]; then
    config_file="/etc/postallow/postallow.conf"
elif [ -f "/usr/local/etc/postallow.conf" ]; then
    config_file="/usr/local/etc/postallow.conf"
elif [ -f "/usr/local/etc/postallow/postallow.conf" ]; then
    config_file="/usr/local/etc/postallow/postallow.conf"
fi

# Read config file options
if [ ! -s $config_file ] ; then
	printf "%s: Can't find %s. Exiting.\n" "$0" "$config_file" 1>&2
	exit 1
fi
printf "\nReading options from %s...\n" "$config_file"
. "${config_file}"

# Read file with hosts that should be allowed
if [ ! -s $allowlist_hosts ] ; then
	printf "%s: Can't find %s. Exiting.\n" "$0" "$allowlist_hosts" 1>&2
	exit 1
fi
printf "\nReading options from %s...\n" "$allowlist_hosts"
. "${allowlist_hosts}"

# Create temporary files
printf "\nCreating temporary files...\n"
tmpBase=$(basename "$0")

tmpPrefix="tmp"
if [ x"$enable_blocklist" = x"yes" ]; then
	tmpPrefix="tmp blktmp"
fi

for p in $tmpPrefix; do
	for i in 1 2 3 4 5; do
		t="$(mktemp -q /tmp/"${tmpBase}".XXXXXX)"
		if [ $? -ne 0 ]; then
			>&2 printf "%s: Can't create temp files, exiting...\n" "$0"
			cleanup
			exit 1
		fi
		eval ${p}${i}="$t"
	done
done

# Create IPv4 normalize function
ip2int() {
	for i in 1 2 3 4 5; do
		eval ip2int_${i}="$(echo "$1" | cut -s -d. -f$i)"
	done
	ip2int_valid_range="$((ip2int_1 | ip2int_2 | ip2int_3 | ip2int_4))"
	[ -z "$ip2int_5" ] && [ -n "$ip2int_1" ] && [ -n "$ip2int_2" ] && [ -n "$ip2int_3" ] && [ -n "$ip2int_4" ] && [ "$ip2int_valid_range" -ge 0 ] && [ "$ip2int_valid_range" -le 255 ] &&
		printf "%d" "$(((((((ip2int_1 << 8) | ip2int_2) << 8) | ip2int_3) << 8) | ip2int_4))"
}

int2ip() {
	int2ip_ui32="$1"; shift
	int2ip_ip=""
	[ -n "$int2ip_ui32" ] && [ "$int2ip_ui32" -ge 0 ] && [ "$int2ip_ui32" -le 4294967295 ] && for n in 1 2 3 4; do
		int2ip_ip="$((int2ip_ui32 & 0xff))${int2ip_ip:+.}$int2ip_ip"
		int2ip_ui32="$((int2ip_ui32 >> 8))"
	done
	printf "%s" "${int2ip_ip}"
}

network_v4() {
	network_v4_ia="$(echo "$1" | cut -d/ -f1)"
	network_v4_netmask="$(echo "$1" | cut -d/ -f2-)"
	if [ -n "$network_v4_netmask" ] && [ "$network_v4_netmask" -ge 0 ] && [ "$network_v4_netmask" -le 32 ]; then
		network_v4_addr="$(ip2int $network_v4_ia)"
		network_v4_mask="$((0xffffffff << (32 - network_v4_netmask)))"
		if [ "$network_v4_netmask" -eq 32 ]; then
			printf "%s" $(int2ip $((network_v4_addr & network_v4_mask)))
		else
			printf "%s/%s" "$(int2ip $((network_v4_addr & network_v4_mask)))" "$network_v4_netmask"
		fi
	fi
}

network_v6() {
	printf "%s" "$1"
}

normalize_ip() {
	# split by ":"
	normalize_ip_type="$( echo $1 | cut -s -d\: -f1)"
	normalize_ip_value="$( echo $1 | cut -s -d\: -f2-)"
	normalize_ip_IP=""
	if [ x"${normalize_ip_type}" = x"ip4" ] ; then
		# check if is a CIDR
		if expr "x${normalize_ip_value}" : "x.*/[0-9]*" > /dev/null; then
			normalize_ip_IP="$(network_v4 "${normalize_ip_value}")"
		else
			normalize_ip_IP="$(network_v4 "${normalize_ip_value}/32")"
		fi
	elif [ x"${normalize_ip_type}" = x"ip6" ]; then
		normalize_ip_IP="$(network_v6 "${normalize_ip_value}")"
	fi
	printf "%s" "$normalize_ip_IP"
}

# Create host query function
query_host() {
	"${spftoolspath}"/despf.sh "$1" | (grep -Ei ^ip || true ) >> "${tmp1}"
}

query_block_host() {
	"${spftoolspath}"/despf.sh "$1" | (grep -Ei ^ip || true ) >> "${blktmp1}"
}

# Create Yahoo query function that pulls their SPF records from their own Nameservers
query_yahoo_host() {
	"${spftoolspath}"/despf.sh -d ns1.yahoo.com "$1" | (grep -Ei ^ip || true ) >> "${tmp1}"
}

# Create progress dots function
show_dots() {
	while ps "$1" >/dev/null; do
		printf "."
		sleep 1
	done
	printf "\n"
}

# Fix mode
fix_invalid_ip() {
	fix_invalid_ip_iptype="$( echo "$1" | cut -d\: -f1 )"
	fix_invalid_ip_ip="$(normalize_ip "$1")"
	if [ -n "$fix_invalid_ip_ip" ]; then
		if [ x"$fix_invalid_ip_iptype" = x"ip4" ]; then
			printf "$(eval printf "%s" "\${${2}_line_v4}")" "$fix_invalid_ip_ip"
		elif [ x"$fix_invalid_ip_iptype" = x"ip6" ] ; then
			printf "$(eval printf "%s" "\${${2}_line_v6}")" "$fix_invalid_ip_ip"
		fi
	fi
}

# Remove mode
remove_invalid_ip() {
	remove_invalid_ip_iptype="$( echo "$1" | cut -d\: -f1 )"
	remove_invalid_ip_origip="$( echo "$1" | cut -d\: -f2- )"
	remove_invalid_ip_ip="$(normalize_ip "$1")"
	if [ x"$remove_invalid_ip_origip" = x"$remove_invalid_ip_ip" ]; then
		if [ x"$remove_invalid_ip_iptype" = x"ip4" ]; then
			printf "$(eval printf "%s" "\${${2}_line_v4}")" "$remove_invalid_ip_ip"
		elif [ x"$remove_invalid_ip_iptype" = x"ip6" ] ; then
			printf "$(eval printf "%s" "\${${2}_line_v6}")" "$remove_invalid_ip_ip"
		fi
	fi
}

# Keep mode
keep_invalid_ip() {
	keep_invalid_ip_iptype="$( echo "$1" | cut -d\: -f1 )"
	keep_invalid_ip_ip="$( echo "$1" | cut -d\: -f2- )"
	if [ -n "$keep_invalid_ip_ip" ]; then
		if [ x"$keep_invalid_ip_iptype" = x"ip4" ]; then
			printf "$(eval printf "%s" "\${${2}_line_v4}")" "$keep_invalid_ip_ip"
		elif [ x"$keep_invalid_ip_iptype" = x"ip6" ] ; then
			printf "$(eval printf "%s" "\${${2}_line_v6}")" "$keep_invalid_ip_ip"
		fi
	fi
}

# Let's DO this!

printf "\nRecursively querying SPF records of selected allowlist mailers...\n"

printf "\nQuerying email hosts...\n"

for h in ${email_hosts}; do
	query_host "${h}"
done

printf "\nQuerying social network hosts...\n"

for h in ${social_hosts}; do
	query_host "${h}"
done

printf "\nQuerying ecommerce hosts...\n"

for h in ${commerce_hosts}; do
	query_host "${h}"
done

printf "\nQuerying bulk mail hosts...\n"

for h in ${bulk_hosts}; do
	query_host "${h}"
done

printf "\nQuerying miscellaneous hosts...\n"

for h in ${misc_hosts}; do
	query_host "${h}"
done

printf "\nQuerying custom hosts...\n"

for h in ${custom_hosts}; do
	query_host "${h}"
done

if [ x"$include_yahoo" = x"yes" ] ; then
	printf "\nIncluding scraped Yahoo! outbound hosts...\n"

	cat "${yahoo_static_hosts}" >> "${tmp1}"
fi

if [ x"$enable_blocklist" = x"yes" ] ; then
	printf "\nQuerying blocklist hosts...\n"

	for h in ${blocklist_hosts}; do
		query_block_host "${h}"
	done
fi

printf "\nCIDR and Host summarization...\n"
# the depends on https://github.com/nabbi/route-summarization with symlink in system PATH
# invalid hosts are also screened and removed
sed '/\./s/\/32//g' "${tmp1}" | sort -u | ${aggregateCIDR} --quiet --spf > "${tmp2}" &
show_dots "$!"

if [ x"$enable_denylist" = x"yes" ] ; then
        cat "${denytmp1}" | sort -u | ${aggregateCIDR} --quiet --spf > "${denytmp2}" &
        show_dots "$!"
fi

#Format the lists
printf "\nFormatting allowlist IPv4 CIDRs...\n"
cat "${tmp2}" | while read ip; do
keep_invalid_ip "$ip" "permit"
done >> "${tmp3}" &
show_dots "$!"

if [ x"$enable_blocklist" = x"yes" ] ; then
	printf "\nFormatting blocklist IPv4 CIDRs...\n"
	cat "${blktmp2}" | while read ip; do
		keep_invalid_ip "$ip" "reject"
	done >> "${blktmp3}" &
	show_dots "$!"
fi

# Sort, uniq, and count final rules
# Have to do sort and uniq separately, as 'sort -u -t. -k1,1n...' removes valid rules
printf "\nSorting allowlist rules...\n"
sort -t. -k1,1n -k2,2n -k3,3n -k4,4n "${tmp3}" > "${tmp4}"
uniq "${tmp4}" >> "${tmp5}"
numrules="$(cat "${tmp5}" | wc -l)"

if [ x"$enable_blocklist" = x"yes" ] ; then
	printf "\nSorting blocklist rules...\n"
	sort -t. -k1,1n -k2,2n -k3,3n -k4,4n "${blktmp3}" > "${blktmp4}"
	uniq "${blktmp4}" >> "${blktmp5}"
	numblockrules="$(cat "${blktmp5}" | wc -l)"
fi

# Write allowlist and blocklist to Postfix directory
printf "\nWriting $numrules allowlist rules to ${postfixpath}/${allowlist}...\n"
printf "# Whitelist generated by Postallow v$version on $(date)\n# https://github.com/lquidfire/postallow/\n# $numrules total rules\n" > "${postfixpath}"/"${allowlist}"
cat "${tmp5}" >> "${postfixpath}"/"${allowlist}"

if [ x"$enable_blocklist" = x"yes" ] ; then
	printf "\nWriting $numblockrules blocklist rules to ${postfixpath}/${blocklist}...\n"
	printf "# Blacklist generated by Postallow v$version on $(date)\n# https://github.com/lquidfire/postallow/\n# $numblockrules total rules\n" > "${postfixpath}"/"${blocklist}"
	cat "${blktmp5}" >> "${postfixpath}"/"${blocklist}"
fi

# Remove temp files
cleanup() {
	test -e "${tmp1}" && rm "${tmp1}"
	test -e "${tmp2}" && rm "${tmp2}"
	test -e "${tmp3}" && rm "${tmp3}"
	test -e "${tmp4}" && rm "${tmp4}"
	test -e "${tmp5}" && rm "${tmp5}"
	if [ x"$enable_blocklist" = x"yes" ] ; then
		test -e "${blktmp1}" && rm "${blktmp1}"
		test -e "${blktmp2}" && rm "${blktmp2}"
		test -e "${blktmp3}" && rm "${blktmp3}"
		test -e "${blktmp4}" && rm "${blktmp4}"
		test -e "${blktmp5}" && rm "${blktmp5}"
	fi
}
cleanup

# Extract all domains from the allowlist, format them from Rspamd, and add them to the ARC configuration file whitelisted_signers_map
#
# 0. ONLY run this if enabled in the configuration file
# 1. Check if a filename was provided in the configuration file
# 2. If no file was proviced, check if default file exists
# 3. Run the script and output it.
# 4. Make use of temp files and move above temp file cleanup
#
# The function to extract the domain names:
extract_domains_line() {
  local input_file="$1"

  # Check if the input file exists
  if [[ ! -f "$input_file" ]]; then
    echo "Error: File not found: $input_file"
    exit 1
  fi

  # Process the file and write to domains_line.txt
  awk '
    BEGIN { ORS = " " }
    /="/ {
      gsub(/.*="/, "")
      inlist = 1
    }
    inlist {
      gsub(/\\/, "")
      printf "%s", $0
    }
    /"/ {
      gsub(/".*/, "")
      print ""
      inlist = 0
    }
  ' "$input_file" |
  tr ' ' '\n' |
  sed -E '
    s/^[[:space:]]+//;
    s/[[:space:]]+$//;
    s/"$//
  ' |
  grep -vE '^$|^_' |
  awk '{ printf "\"%s\", ", $0 }' |
  sed 's/, $//' > domains_line.txt

  # Add a final newline
  echo >> domains_line.txtV

}

# Reload Postfix to pick up changes in allowlist
if [ x"$reload_postfix" = x"yes" ]; then
printf '\nReloading Postfix configuration to refresh rules...\n'
	sudo ${postfixbinarypath}/postfix reload
fi

printf '\nDone!\n'

exit
