.\" A license should / could go here...
.\"
.TH POSTALLOW 1 "version 0.1" "April 2025"

.SH NAME
Postallow \- Postallow generates an allowlist for Postfix's Postscreen (8), 
based on large senders' SPF records

.SH SYNOPSIS
.B Postallow
.RI [ file ] " \fIoptional"

.SH DESCRIPTION
\fBPostallow\fR is a script that generates an allowlist for Postfix's 
Postscreen (8), based on large senders' SPF records.
.sp
Sender domains can easily be added or removed via the file 
\fIallowlist_hosts\fR.

.SH FILES
When a configuration file \fIpostallow.conf\fR is given on the command line, 
\fBPostallow\fR reads the specified file for setting its options and file 
locations.  Without that option, \fBPostallow\fR tries to find the configuration 
file in the following locations: either \fI/etc/postallow.conf\fR , or 
\fI/etc/postallow/postallow.conf\fR , or \fI/usr/local/etc/postallow.conf\fR , 
or \fI/usr/local/etc/postallow/postallow.conf\fR .  See
.BR postallow.conf (5)
for more information on the configuration options of \fBPostallow\fR .

.SH BUGS
Please report any bugs that you encounter via:
.br
.IR https://github.com/lquidfire/postallow/ .

.SH HOMEPAGE
.I https://github.com/lquidfire/postallow/

.SH SEE ALSO
.BR postallow.conf (5)
.sp
\fI/usr/share/doc/postallow/\fR (or equivalent on your system)
